# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: ForgeFlow
org_slug: ForgeFlow
rebel_module_groups: []
repo_description: Know Your Customer (KYC) Odoo addons.
repo_name: Know Your Customer
repo_slug: know-your-customer
repo_website: https://github.com/ForgeFlow/know-your-customer
travis_apt_packages: []
travis_apt_sources: []

